version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: latex-backend
    working_dir: /app
  
    ports:
      - "8000:8000"
    #command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
  